### ISSUE TITLE
嗨，您好大神

### ISSUE THREAD

**Issue by liuchangxing** [simon-xia/atom-global-background#2]
请问透明度要改哪段代码呢，这个插件我特别喜欢，就是背景图有点不清晰，我想改的清楚些，能告诉我吗，好人一生平安
![qq 20161017193756](https://cloud.githubusercontent.com/assets/22342099/19436159/25a81f54-94a1-11e6-8765-fb26a0aada9a.png)
！

**Comment by liuchangxing** [comment]
再清晰点就好了……

**Comment by liuchangxing** [comment]
![qq 20161017193756](https://cloud.githubusercontent.com/assets/22342099/19436431/a6194de2-94a2-11e6-9e02-9aa0e0204c69.png)
好吧我自己调了下，调好了……

**Comment by simon-xia** [comment]
额， 刚上来看到你的issue，改下 `./styles/global-backaground.less` 里的 `opacity` 值就 ok
